###GET users 
GET http://localhost:1234/api/users

###GET users by ID
GET http://localhost:1234/api/users/4

###POST create new user
POST http://localhost:1234/api/users
Content-Type: application/json

{
  "username": "Sara",
  "email": "sara@example.com"
}

###PUT update user by ID
PUT http://localhost:1234/api/users/3
Content-Type: application/json

{
  "username": "Jose",
  "email": "Jose@example.com"   
}   

###DELETE user by ID
DELETE http://localhost:1234/api/users/4